//
//  LanguageCodeList.swift
//
//
//  Created by moizhassnkh on 09/10/23.
//

import Foundation
import UIKit

public enum LanguageCode: String, EnumComposable {
    case Afar
    case Abkhaz
    case Avestan
    case Afrikaans
    case Akan
    case Amharic
    case Aragonese
    case Arabic
    case Avaric
    case Aymara
    case Azerbaijani
    case Bashkir
    case Belarusian
    case Bulgarian
    case Bihari
    case Bislama
    case Bambara
    case Bengali
    case Tibetan
    case Breton
    case Bosnian
    case Catalan
    case Chechen
    case Chamorro
    case Corsican
    case Cree
    case Czech
    case Slavonic
    case Chuvash
    case Welsh
    case Danish
    case German
    case Maldivian
    case Dzongkha
    case Ewe
    case Greek
    case English
    case Esperanto
    case Spanish
    case Estonian
    case Basque
    case Persian
    case Fulah
    case Finnish
    case Fijian
    case Faroese
    case French
    case WesternFrisian
    case Irish
    case Gaelic
    case Galician
    case Guarani
    case Gujarati
    case Manx
    case Hausa
    case Hebrew
    case Hindi
    case HiriMotu
    case Croatian
    case Haitian
    case Hungarian
    case Armenian
    case HereroR
    case Interlingua
    case Indonesian
    case Occidental
    case Igbo
    case Nuosu
    case Inupiaq
    case Ido
    case Icelandic
    case Italian
    case Inuktitut
    case Japanese
    case Javanese
    case Georgian
    case Kongo
    case Kikuyu
    case Kuanyama
    case Kazakh
    case Greenlandic
    case CentralKhmer
    case Kannada
    case Korean
    case Kanuri
    case Kashmiri
    case Kurdish
    case Komi
    case Cornish
    case Kirghiz
    case Latin
    case Luxembourgish
    case Ganda
    case Limburgish
    case Lingala
    case Lao
    case Lithuanian
    case LubaKatanga
    case Latvian
    case Malagasy
    case Marshallese
    case Maori
    case Macedonian
    case Malayalam
    case Mongolian
    case Moldavian
    case Marathi
    case Malay
    case Maltese
    case Burmese
    case Nauruan
    case NorwegianBokmal
    case NorthNdebele
    case Nepali
    case Ndonga
    case Dutch
    case NorwegianNynorsk
    case Norwegian
    case SouthNdebele
    case Navajo
    case Nyanja
    case Occitan
    case Ojibwa
    case Oromo
    case Oriya
    case Ossetian
    case Punjabi
    case Pali
    case Polish
    case Pushto
    case Portuguese
    case Quechua
    case Reunionese
    case Romansh
    case Rundi
    case Romanian
    case Russian
    case Kinyarwanda
    case Sanskrit
    case Sardinian
    case Sindhi
    case NorthernSami
    case Sango
    case Slavic
    case Sinhalese
    case Slovak
    case Slovenian
    case Samoan
    case Shona
    case Somali
    case Albanian
    case Serbian
    case Swati
    case SouthernSotho
    case Sundanese
    case Swedish
    case Swahili
    case Tamil
    case Telugu
    case Tajik
    case Thai
    case Tigrinya
    case Turkmen
    case Tagalog
    case Tswana
    case Tongan
    case Turkish
    case Tsonga
    case Tatar
    case Twi
    case Tahitian
    case Uighur
    case Ukrainian
    case Urdu
    case Uzbek
    case Venda
    case Vietnamese
    case Volapuk
    case Walloon
    case Wolof
    case Xhosa
    case Yiddish
    case Yoruba
    case Zhuang
    case Chinese
    case Zulu

}
